(function(){
  'use strict';
  var NOAA_OBS='https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json';
  var NOAA_FC='https://services.swpc.noaa.gov/products/noaa-planetary-k-index-forecast.json';
  var weather=null,kp={current:null,forecast:{}};
  function $(id){return document.getElementById(id)}
  function n(v){v=Number(v);return Number.isFinite(v)?v:null}
  function val(v,s){return n(v)===null?'Indisponível':(Math.round(Number(v)*10)/10)+(s||'')}
  function cardinal(v){var a=['N','NE','L','SE','S','SO','O','NO'];return a[Math.round((Number(v)||0)/45)%8]}
  function selectedDay(){var d=$('flightDate');return d&&d.value||new Date().toISOString().slice(0,10)}
  function dayIndex(day){var times=weather&&weather.daily&&weather.daily.time||[];var i=times.indexOf(day);return i<0?0:i}
  function dayValues(day,key){var h=weather&&weather.hourly||{},t=h.time||[],v=h[key]||[];return t.map(function(x,i){return x&&x.slice(0,10)===day?n(v[i]):null}).filter(function(x){return x!==null})}
  function visibility(day){var a=dayValues(day,'visibility');return a.length?Math.min.apply(null,a)/1000:null}
  function clouds(day){var a=dayValues(day,'cloud_cover');return a.length?a.reduce(function(x,y){return x+y},0)/a.length:null}
  function kpDay(day){return n(kp.forecast[day])!==null?n(kp.forecast[day]):kp.current}
  function kpInfo(v){v=n(v);if(v===null)return['amber','Indisponível','Sem leitura geomagnética'];if(v<=2)return['green','Excelente','GNSS favorável'];if(v===3)return['green','Muito bom','Sem impacto esperado'];if(v===4)return['amber','Atenção','Possíveis oscilações GNSS'];if(v===5)return['orange','Tempestade G1','Possível perda de precisão'];return['red','Crítico','Evite operações GNSS críticas']}
  function windLimit(){var s=$('droneSelect');if(!s)return 0;var o=s.options[s.selectedIndex];return Number(o&&o.dataset.limit)||Number($('manualWindLimit')&&$('manualWindLimit').value)||0}
  function score(i){var d=weather.daily,day=d.time[i],gust=n(d.wind_gusts_10m_max[i])||0,rain=n(d.precipitation_probability_max[i])||0,mm=n(d.precipitation_sum[i])||0,vis=visibility(day),k=kpDay(day),lim=windLimit(),x=100;
    if(lim){var r=gust/lim;x-=r<=.55?r*12:r<=.8?12+(r-.55)*55:r<=1?26+(r-.8)*110:48+(r-1)*90}else{x-=Math.max(0,gust-18)*1.2}
    x-=rain*.22;x-=Math.min(18,mm*2.5);if(vis!==null)x-=vis>=8?0:vis>=5?6:vis>=3?15:28;if(k!==null)x-=k<=3?0:k===4?8:k===5?18:30;return Math.max(0,Math.min(100,Math.round(x)))}
  function status(s){return s>=85?['green','Excelente','Decole']:s>=70?['amber','Bom','Decole com atenção']:s>=50?['orange','Atenção','Somente pilotos experientes']:['red','Não recomendado','Voo não recomendado']}
  function stars(s){var k=Math.max(1,Math.ceil(s/20));return '★'.repeat(k)+'☆'.repeat(5-k)}
  function injectStyles(){if($('opsWeatherStyles'))return;var e=document.createElement('style');e.id='opsWeatherStyles';e.textContent='.forecast-card{min-height:245px!important;display:flex!important;flex-direction:column!important;gap:7px!important;text-align:left!important}.forecast-card__row{display:flex;justify-content:space-between;gap:10px;font-size:.72rem;color:var(--text2)}.forecast-card__row b{color:var(--text)}.forecast-card__top{display:flex;justify-content:space-between;align-items:center}.forecast-card__kp{padding:6px 8px;border-radius:8px;background:rgba(0,210,255,.06);border:1px solid rgba(0,210,255,.12)}.ops-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.ops-card{background:var(--bg);border:1px solid var(--border);border-radius:14px;padding:15px}.ops-card span{display:block;color:var(--text3);font-size:.64rem;text-transform:uppercase}.ops-card strong{display:block;margin:7px 0;font-family:var(--title)}.ops-card small{color:var(--text2);line-height:1.4}.ops-alerts{display:grid;gap:8px;margin-top:14px}.ops-alert{padding:10px 12px;border-radius:9px;border:1px solid var(--border);font-size:.78rem}.ops-alert.red{background:rgba(240,68,56,.08);color:#ffaaa4}.ops-alert.orange{background:rgba(249,115,22,.08);color:#fdba74}.ops-alert.amber{background:rgba(255,176,32,.08);color:#fcd34d}.ops-alert.green{background:rgba(52,211,153,.06);color:#86efac}@media(max-width:900px){.ops-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.ops-grid{grid-template-columns:1fr}}';document.head.appendChild(e)}
  function mountAltitude(){var target=document.querySelector('.conditions-card');if(!target||$('altitudeProfile'))return;var el=document.createElement('section');el.id='altitudeProfile';el.className='altitude-profile';el.innerHTML='<div class="altitude-profile__head"><span>PERFIL DE VENTO · ALTITUDE OPERACIONAL</span><small id="altitudeStamp">Consultando leitura</small></div><div id="altitudeGrid" class="altitude-profile__grid"><div class="altitude-profile__item"><span>50 m</span><b>—</b><small>Carregando</small></div><div class="altitude-profile__item"><span>80 m</span><b>—</b><small>Carregando</small></div><div class="altitude-profile__item"><span>120 m</span><b>—</b><small>Carregando</small></div></div>';target.appendChild(el)}
  function renderAltitude(){var lat=Number(localStorage.getItem('dronehub_lat'))||-22.9068,lon=Number(localStorage.getItem('dronehub_lon'))||-43.1729;fetch('https://api.open-meteo.com/v1/forecast?latitude='+lat+'&longitude='+lon+'&hourly=wind_speed_10m,wind_direction_10m,wind_speed_80m,wind_direction_80m,wind_speed_120m,wind_direction_120m,visibility&forecast_hours=1&timezone=auto').then(function(r){return r.json()}).then(function(data){var h=data.hourly||{},g=$('altitudeGrid');if(!g)return;var rows=[['50 m',h.wind_speed_10m&&h.wind_speed_10m[0],h.wind_direction_10m&&h.wind_direction_10m[0]],['80 m',h.wind_speed_80m&&h.wind_speed_80m[0],h.wind_direction_80m&&h.wind_direction_80m[0]],['120 m',h.wind_speed_120m&&h.wind_speed_120m[0],h.wind_direction_120m&&h.wind_direction_120m[0]]];g.innerHTML=rows.map(function(x){return '<div class="altitude-profile__item"><span>'+x[0]+'</span><b>'+Math.round(x[1]||0)+' km/h</b><small>'+cardinal(x[2])+' · '+Math.round(x[2]||0)+'°</small></div>'}).join('');var v=h.visibility&&h.visibility[0];$('altitudeStamp').textContent='Visibilidade '+(v?Math.max(.1,Math.round(v/100)/10)+' km':'indisponível')+' · atualizado agora'}).catch(function(){if($('altitudeStamp'))$('altitudeStamp').textContent='Leitura de altitude indisponível agora'})}
  function fetchKp(){return Promise.allSettled([fetch(NOAA_OBS).then(function(r){if(!r.ok)throw Error();return r.json()}),fetch(NOAA_FC).then(function(r){if(!r.ok)throw Error();return r.json()})]).then(function(r){if(r[0].status==='fulfilled'){var a=r[0].value,last=Array.isArray(a)?a.slice(1).reverse().find(function(x){return Number.isFinite(Number(x&&x[1]))}):null;if(last)kp.current=Number(last[1])}if(r[1].status==='fulfilled'&&Array.isArray(r[1].value)){r[1].value.forEach(function(x){if(!x||!x[0]||!Number.isFinite(Number(x[1])))return;var day=String(x[0]).slice(0,10);kp.forecast[day]=Math.max(kp.forecast[day]||0,Number(x[1]))})}renderOps()})}
  function alerts(i){var d=weather.daily,day=d.time[i],gust=n(d.wind_gusts_10m_max[i])||0,rain=n(d.precipitation_probability_max[i])||0,vis=visibility(day),k=kpDay(day),lim=windLimit(),a=[];if(lim&&gust>lim)a.push(['red','Rajadas acima do limite cadastrado da aeronave.']);else if(lim&&gust/lim>=.8)a.push(['orange','Rajadas próximas do limite operacional da aeronave.']);if(rain>=70)a.push(['red','Alta probabilidade de chuva: '+Math.round(rain)+'%.']);else if(rain>=40)a.push(['amber','Possibilidade relevante de chuva: '+Math.round(rain)+'%.']);if(vis!==null&&vis<5)a.push(['red','Visibilidade reduzida: '+val(vis,' km')+'.']);if(k!==null&&k>=5)a.push(['red','KP '+val(k)+': possível degradação GNSS/RTK/RTH.']);else if(k===4)a.push(['amber','KP 4: monitore a precisão GNSS.']);if(!a.length)a.push(['green','Nenhum alerta operacional crítico identificado.']);return a}
  function renderForecast(){var g=$('forecastGrid');if(!g||!weather||!weather.daily)return;var d=weather.daily,selected=selectedDay();g.innerHTML=d.time.map(function(day,i){var s=score(i),st=status(s),k=kpDay(day),ki=kpInfo(k),vis=visibility(day),cloud=clouds(day);return '<button type="button" class="weather-item forecast-card risk-'+st[0]+'" data-day="'+day+'"><div class="forecast-card__top"><strong>'+new Date(day+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'})+'</strong><b>'+s+'/100</b></div><span style="color:var(--'+st[0]+');font-weight:700">'+st[1]+'</span><div class="forecast-card__row"><span>Vento</span><b>'+Math.round(d.wind_speed_10m_max[i]||0)+' km/h</b></div><div class="forecast-card__row"><span>Rajadas</span><b>'+Math.round(d.wind_gusts_10m_max[i]||0)+' km/h</b></div><div class="forecast-card__row"><span>Chuva</span><b>'+Math.round(d.precipitation_probability_max[i]||0)+'% · '+val(d.precipitation_sum[i],' mm')+'</b></div><div class="forecast-card__row"><span>Visibilidade</span><b>'+val(vis,' km')+'</b></div><div class="forecast-card__row"><span>Nuvens</span><b>'+val(cloud,'%')+'</b></div><div class="forecast-card__row"><span>UV máximo</span><b>'+val(d.uv_index_max[i])+'</b></div><div class="forecast-card__row forecast-card__kp"><span>Índice KP</span><b>'+val(k)+' · '+ki[1]+'</b></div><div class="forecast-card__row"><span>Luz do dia</span><b>'+Math.floor((d.daylight_duration[i]||0)/3600)+'h</b></div></button>'}).join('');Array.from(g.querySelectorAll('[data-day]')).forEach(function(b){b.addEventListener('click',function(){if($('flightDate'))$('flightDate').value=b.dataset.day;renderOps()})})}
  function renderOps(){if(!weather||!weather.daily)return;var day=selectedDay(),i=dayIndex(day),s=score(i),st=status(s),k=kpDay(day),ki=kpInfo(k),d=weather.daily,lim=windLimit(),gust=n(d.wind_gusts_10m_max[i])||0,usage=lim?Math.round(gust/lim*100):null,photo=Math.max(0,Math.min(100,s+(visibility(day)>=10?7:0)-(clouds(day)>85?10:0))),inspect=Math.max(0,Math.min(100,s-Math.max(0,(k||0)-3)*6)),spray=Math.max(0,Math.min(100,100-Math.max(0,(d.wind_speed_10m_max[i]||0)-10)*4-Math.max(0,gust-18)*4-(d.precipitation_probability_max[i]||0)*.4));var target=document.querySelector('.conditions-card');if(!target)return;var sec=$('opsAssistant');if(!sec){sec=document.createElement('section');sec.id='opsAssistant';sec.className='card';target.insertAdjacentElement('afterend',sec)}sec.innerHTML='<div class="card-header"><h3>Assistente operacional</h3><span class="status-badge '+st[0]+'">'+st[2]+'</span></div><div class="ops-grid"><div class="ops-card"><span>Score operacional</span><strong>'+s+'/100 · '+st[1]+'</strong><small>Vento, chuva, visibilidade, KP e limite da aeronave.</small></div><div class="ops-card"><span>Aeronave</span><strong>'+(lim?'Uso previsto: '+usage+'%':'Selecione uma aeronave')+'</strong><small>'+(lim?'Limite cadastrado: '+val(lim,' km/h'):'A avaliação específica depende do limite do fabricante.')+'</small></div><div class="ops-card"><span>Fotografia aérea</span><strong>'+stars(photo)+'</strong><small>'+Math.round(photo)+'/100 · luz, nuvens, vento e visibilidade.</small></div><div class="ops-card"><span>Inspeção</span><strong>'+Math.round(inspect)+'/100</strong><small>Estabilidade, visibilidade e GNSS.</small></div><div class="ops-card"><span>Pulverização</span><strong>'+Math.round(spray)+'/100</strong><small>Vento, rajadas e chuva.</small></div><div class="ops-card"><span>Atividade geomagnética</span><strong>KP '+val(k)+' · '+ki[1]+'</strong><small>'+ki[2]+'</small></div></div><div class="ops-alerts">'+alerts(i).map(function(a){return '<div class="ops-alert '+a[0]+'">'+a[1]+'</div>'}).join('')+'</div>';if($('flightRiskScore'))$('flightRiskScore').textContent=s+'/100';if($('flightRiskLabel'))$('flightRiskLabel').textContent=st[1];if($('statusBadge')){$('statusBadge').className='status-badge '+st[0];$('statusBadge').textContent=st[2]}renderForecast()}
  function bind(){window.addEventListener('dronehub:weather-ready',function(e){weather=e.detail;fetchKp().finally(renderOps)});document.addEventListener('change',function(e){if(e.target&&['flightDate','droneSelect','manualWindLimit'].indexOf(e.target.id)>=0)setTimeout(renderOps,0)});if(window.DroneHubFlightWeather){weather=window.DroneHubFlightWeather;fetchKp().finally(renderOps)}}
  document.addEventListener('DOMContentLoaded',function(){injectStyles();mountAltitude();renderAltitude();bind();setInterval(renderAltitude,10*60*1000);setInterval(fetchKp,10*60*1000)});
}());
