(function(){
'use strict';
var weather=null,kpCurrent=0,kpForecast={};
var NOAA_OBS='https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json';
var NOAA_FC='https://services.swpc.noaa.gov/products/noaa-planetary-k-index-forecast.json';
function $(id){return document.getElementById(id)}
function num(v){v=Number(v);return Number.isFinite(v)?v:null}
function dayIndex(day){var t=weather&&weather.daily&&weather.daily.time||[];var i=t.indexOf(day);return i<0?0:i}
function selectedDay(){return $('flightDate')&&$('flightDate').value||(weather&&weather.daily&&weather.daily.time&&weather.daily.time[0])||new Date().toISOString().slice(0,10)}
function dayVals(day,key){var h=weather&&weather.hourly||{},t=h.time||[],a=h[key]||[];return t.map(function(x,i){return x&&x.slice(0,10)===day?num(a[i]):null}).filter(function(x){return x!==null})}
function minVis(day){var a=dayVals(day,'visibility');return a.length?Math.min.apply(null,a)/1000:null}
function avgCloud(day){var a=dayVals(day,'cloud_cover');return a.length?a.reduce(function(x,y){return x+y},0)/a.length:null}
function kpFor(day){return num(kpForecast[day])!==null?num(kpForecast[day]):kpCurrent}
function kpMeta(k){k=num(k)||0;if(k<=2)return['green','Excelente'];if(k===3)return['blue','Muito bom'];if(k===4)return['yellow','Atenção'];if(k===5)return['red','Geomagnético'];return['red','Crítico']}
function aircraft(){var s=$('droneSelect');if(!s)return{name:'Selecione uma aeronave',limit:0};var o=s.options[s.selectedIndex];return{name:o&&o.dataset.model||o&&o.text||'Selecione uma aeronave',limit:Number(o&&o.dataset.limit)||Number($('manualWindLimit')&&$('manualWindLimit').value)||0}}
function score(i){var d=weather.daily,day=d.time[i],gust=num(d.wind_gusts_10m_max[i])||0,rain=num(d.precipitation_probability_max[i])||0,mm=num(d.precipitation_sum[i])||0,vis=minVis(day),k=kpFor(day),a=aircraft(),x=100;if(a.limit){var r=gust/a.limit;x-=r<=.55?r*12:r<=.8?12+(r-.55)*50:r<=1?25+(r-.8)*100:50+(r-1)*100}else{x-=Math.max(0,gust-18)*1.15}x-=rain*.2;x-=Math.min(16,mm*2.2);if(vis!==null)x-=vis>=8?0:vis>=5?6:vis>=3?15:28;if(k>=4)x-=k===4?8:k===5?18:30;return Math.max(0,Math.min(100,Math.round(x)))}
function status(s){return s>=85?['green','Excelente','EXCELENTE PARA VOO']:s>=70?['blue','Bom','BOAS CONDIÇÕES']:s>=50?['yellow','Atenção','VOE COM ATENÇÃO']:['red','Não recomendado','VOO NÃO RECOMENDADO']}
function weatherIcon(code){code=Number(code)||0;if(code===0)return'☀️';if(code<=3)return'⛅';if(code<=48)return'🌫️';if(code<=67)return'🌧️';if(code<=77)return'🌨️';if(code<=82)return'🌦️';return'⛈️'}
function fmt(v,s){return num(v)===null?'—':(Math.round(Number(v)*10)/10)+(s||'')}
function time(v){if(!v)return'—';var d=new Date(v);return d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function stars(s){var n=Math.max(1,Math.min(5,Math.round(s/20)));return'★'.repeat(n)+'☆'.repeat(5-n)}
function icon(name){return'<i data-lucide="'+name+'"></i>'}
function mount(){var main=document.querySelector('.main');if(!main||$('flightCommand'))return;var wrap=document.createElement('div');wrap.id='flightCommand';wrap.innerHTML='<div class="fc-head"><div><h1>Central de Voo</h1><p>Centro de decisão operacional</p></div><div class="fc-live">Atualizado agora</div></div><section id="fcSummary" class="fc-panel fc-summary"></section><section class="fc-panel fc-section"><div class="fc-section-title"><b>JANELA OPERACIONAL · PRÓXIMOS 4 DIAS</b><span>Selecione o dia para atualizar a análise</span></div><div id="fcDays" class="fc-days"></div></section><section id="fcMissions" class="fc-mission-grid"></section><section id="fcBottom" class="fc-bottom"></section>';main.insertBefore(wrap,main.firstChild)}
function renderSummary(i){var d=weather.daily,s=score(i),st=status(s),a=aircraft(),day=d.time[i],gust=num(d.wind_gusts_10m_max[i])||0,usage=a.limit?Math.round(gust/a.limit*100):0;$('fcSummary').innerHTML='<div><div class="fc-status-icon">'+icon('shield-check')+'</div><div><span class="fc-kicker">Status geral</span><div class="fc-status-main" style="color:var(--fc-'+st[0]+')">'+st[2]+'</div><div class="fc-sub">Análise integrada de clima, aeronave e atividade geomagnética</div></div></div><div><div class="fc-ring" style="--p:'+s+';--c:var(--fc-'+st[0]+')"><div>'+s+'<small>/100</small></div></div><div><span class="fc-kicker">Score operacional</span><strong>'+st[1]+'</strong></div></div><div><div class="fc-aircraft-icon">🚁</div><div><span class="fc-kicker">Aeronave ativa</span><strong>'+a.name+'</strong><div class="fc-sub">'+(a.limit?'Utilização prevista '+usage+'%':'Selecione no painel abaixo')+'</div></div></div><div><div class="fc-aircraft-icon">'+icon('clock-3')+'</div><div><span class="fc-kicker">Última atualização</span><strong>'+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+'</strong><div class="fc-sub">Atualização automática a cada 10 min</div></div></div>'}
function renderDays(){var d=weather.daily,sel=selectedDay();$('fcDays').innerHTML=d.time.slice(0,4).map(function(day,i){var s=score(i),st=status(s),k=kpFor(day),km=kpMeta(k),vis=minVis(day),cloud=avgCloud(day),code=d.weather_code&&d.weather_code[i],temp=d.temperature_2m_max&&d.temperature_2m_max[i];return'<article class="fc-day '+st[0]+' '+(day===sel?'active':'')+'" data-day="'+day+'"><div class="fc-day-head"><div class="fc-date">'+new Date(day+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'}).toUpperCase()+'</div><div class="fc-score" style="--score:'+s+';--tone:var(--fc-'+st[0]+')">'+s+'/100</div></div><div class="fc-weather-main"><span class="ico">'+weatherIcon(code)+'</span><span class="fc-temp">'+fmt(temp,'°')+'</span><span class="fc-badge '+st[0]+'">'+st[1]+'</span></div><div class="fc-rows"><div class="fc-row"><i>≋</i><span>Vento</span><strong>'+fmt(d.wind_speed_10m_max[i],' km/h')+'</strong></div><div class="fc-row"><i>≋</i><span>Rajadas</span><strong>'+fmt(d.wind_gusts_10m_max[i],' km/h')+'</strong></div><div class="fc-row"><i>☂</i><span>Chuva</span><strong>'+fmt(d.precipitation_probability_max[i],'%')+' · '+fmt(d.precipitation_sum[i],' mm')+'</strong></div><div class="fc-row"><i>◉</i><span>Visibilidade</span><strong>'+fmt(vis,' km')+'</strong></div><div class="fc-row"><i>☁</i><span>Nuvens</span><strong>'+fmt(cloud,'%')+'</strong></div><div class="fc-row"><i>☀</i><span>UV máximo</span><strong>'+fmt(d.uv_index_max[i])+'</strong></div><div class="fc-row fc-kp"><i>⌁</i><span>Índice KP</span><strong>'+fmt(k)+' · '+km[1]+'</strong></div><div class="fc-row"><i>◒</i><span>Nascer do sol</span><strong>'+time(d.sunrise[i])+'</strong></div><div class="fc-row"><i>◓</i><span>Pôr do sol</span><strong>'+time(d.sunset[i])+'</strong></div><div class="fc-row"><i>◷</i><span>Luz do dia</span><strong>'+Math.floor((d.daylight_duration[i]||0)/3600)+'h '+Math.round(((d.daylight_duration[i]||0)%3600)/60)+'m</strong></div></div></article>'}).join('');Array.from(document.querySelectorAll('.fc-day')).forEach(function(c){c.onclick=function(){if($('flightDate'))$('flightDate').value=c.dataset.day;render()}})}
function renderMissions(i){var d=weather.daily,day=d.time[i],s=score(i),st=status(s),a=aircraft(),gust=num(d.wind_gusts_10m_max[i])||0,usage=a.limit?Math.round(gust/a.limit*100):0,vis=minVis(day)||0,cloud=avgCloud(day)||0,k=kpFor(day),photo=Math.max(0,Math.min(100,s+(vis>=10?8:0)-(cloud>80?12:0))),inspect=Math.max(0,Math.min(100,s-Math.max(0,k-3)*5)),spray=Math.max(0,Math.min(100,100-Math.max(0,gust-18)*4-(d.precipitation_probability_max[i]||0)*.45));$('fcMissions').innerHTML='<section class="fc-panel fc-card"><div class="fc-card-title">Avaliação da aeronave</div><div class="fc-card-icon">🚁</div><strong>'+a.name+'</strong><p>'+(a.limit?'Limite do fabricante '+fmt(a.limit,' km/h'):'Selecione uma aeronave para análise específica')+'</p><div class="fc-progress"><b style="width:'+Math.min(100,usage)+'%"></b></div><p>'+usage+'% de utilização prevista</p></section><section class="fc-panel fc-card"><div class="fc-card-title">Índice de decolagem</div><div class="fc-card-icon">🚀</div><strong style="color:var(--fc-'+st[0]+')">'+(s>=85?'DECOLE':s>=70?'DECOLE COM ATENÇÃO':s>=50?'PILOTOS EXPERIENTES':'NÃO RECOMENDADO')+'</strong><div class="fc-checks"><span>Vento analisado</span><span>Rajadas verificadas</span><span>KP considerado</span><span>Visibilidade avaliada</span></div></section><section class="fc-panel fc-card"><div class="fc-card-title">Fotografia</div><div class="fc-card-icon">📷</div><strong style="color:var(--fc-yellow)">'+stars(photo)+'</strong><p>'+Math.round(photo)+'/100 · luz, nuvens, visibilidade e vento.</p><div class="fc-checks"><span>Luz operacional</span><span>Visibilidade '+fmt(vis,' km')+'</span><span>Nuvens '+fmt(cloud,'%')+'</span></div></section><section class="fc-panel fc-card"><div class="fc-card-title">Inspeção</div><div class="fc-card-icon">🛡️</div><strong>'+Math.round(inspect)+'/100</strong><p>Estabilidade, GNSS e visibilidade para inspeções técnicas.</p><div class="fc-checks"><span>KP '+fmt(k)+'</span><span>Rajadas '+fmt(gust,' km/h')+'</span><span>Visibilidade monitorada</span></div></section><section class="fc-panel fc-card"><div class="fc-card-title">Pulverização</div><div class="fc-card-icon">💧</div><strong style="color:var(--fc-'+(spray>=70?'green':spray>=50?'yellow':'red')+')">'+Math.round(spray)+'/100</strong><p>Vento, deriva, rajadas e probabilidade de chuva.</p><div class="fc-checks '+(spray<50?'bad':'')+'"><span>Vento operacional</span><span>Risco de deriva</span><span>Chuva prevista</span></div></section>'}
function renderBottom(i){var d=weather.daily,day=d.time[i],k=kpFor(day),km=kpMeta(k),alerts=[],gust=num(d.wind_gusts_10m_max[i])||0,rain=num(d.precipitation_probability_max[i])||0,vis=minVis(day);if(gust>=40)alerts.push('Rajadas elevadas: '+fmt(gust,' km/h'));if(rain>=40)alerts.push('Chuva prevista: '+fmt(rain,'%'));if(k>=4)alerts.push('KP '+fmt(k)+' · '+km[1]);if(vis!==null&&vis<5)alerts.push('Visibilidade reduzida: '+fmt(vis,' km'));if(!alerts.length)alerts.push('Nenhum alerta crítico no período');$('fcBottom').innerHTML='<section class="fc-panel fc-card"><div class="fc-card-title">Satélites GNSS</div><div class="fc-gnss"><div class="fc-list"><div><span>GPS</span><b>23</b></div><div><span>GLONASS</span><b>18</b></div><div><span>Galileo</span><b>12</b></div><div><span>BeiDou</span><b>15</b></div><div><span>Total estimado</span><b>68</b></div></div><div class="fc-radar"></div></div></section><section class="fc-panel fc-card"><div class="fc-card-title">Índice KP</div><div class="fc-card-icon">🛰️</div><strong style="color:var(--fc-'+km[0]+')">'+fmt(k)+' · '+km[1]+'</strong><p>Atividade geomagnética aplicada à avaliação GNSS.</p></section><section class="fc-panel fc-card"><div class="fc-card-title">Sol</div><div class="fc-card-icon">☀️</div><div class="fc-list"><div><span>Nascer</span><b>'+time(d.sunrise[i])+'</b></div><div><span>Pôr</span><b>'+time(d.sunset[i])+'</b></div><div><span>Duração</span><b>'+Math.floor((d.daylight_duration[i]||0)/3600)+'h</b></div></div></section><section class="fc-panel fc-card"><div class="fc-card-title">Lua</div><div class="fc-card-icon">🌙</div><strong>Fase lunar</strong><p>Painel preparado para dados astronômicos e fotografia noturna.</p></section><section class="fc-panel fc-card"><div class="fc-card-title">Alertas</div><div class="fc-alerts">'+alerts.map(function(a){return'<div class="fc-alert">'+a+'</div>'}).join('')+'</div></section>'}
function render(){if(!weather||!weather.daily)return;mount();var i=dayIndex(selectedDay());renderSummary(i);renderDays();renderMissions(i);renderBottom(i);if(window.lucide)window.lucide.createIcons()}
function fetchKp(){return Promise.allSettled([fetch(NOAA_OBS).then(function(r){return r.json()}),fetch(NOAA_FC).then(function(r){return r.json()})]).then(function(r){if(r[0].status==='fulfilled'){var a=r[0].value,last=Array.isArray(a)?a.slice(1).reverse().find(function(x){return Number.isFinite(Number(x&&x[1]))}):null;if(last)kpCurrent=Number(last[1])}if(r[1].status==='fulfilled'&&Array.isArray(r[1].value)){r[1].value.forEach(function(x){if(!x||!x[0]||!Number.isFinite(Number(x[1])))return;var day=String(x[0]).slice(0,10);kpForecast[day]=Math.max(kpForecast[day]||0,Number(x[1]))})}render()}).catch(render)}
function bind(){window.addEventListener('dronehub:weather-ready',function(e){weather=e.detail;fetchKp()});document.addEventListener('change',function(e){if(e.target&&['flightDate','droneSelect','manualWindLimit'].indexOf(e.target.id)>=0)setTimeout(render,0)});if(window.DroneHubFlightWeather){weather=window.DroneHubFlightWeather;fetchKp()}}
document.addEventListener('DOMContentLoaded',function(){mount();bind();setInterval(fetchKp,10*60*1000)});
}());
