(function(){
  'use strict';
  var FEATURES={hourly:1,risk:1,documents:1,batteries:1,checklist:1,briefing:1,report:1,save:1};
  function current(){try{return JSON.parse(localStorage.getItem('dronehub_user')||'{}')}catch(e){return {}}}
  function actualTier(){var u=current();return u.role==='admin'?'admin':u.plan==='pro'?'pro':'free'}
  function previewTier(){var real=actualTier();if(real!=='admin')return real;return sessionStorage.getItem('dronehub_admin_preview_tier')||'admin'}
  function premium(tier){return tier==='pro'||tier==='admin'}
  async function refresh(){if(typeof syncCurrentEntitlement==='function'){try{await syncCurrentEntitlement()}catch(e){}}return actualTier()}
  async function requireFeature(name){await refresh();var tier=actualTier();if(FEATURES[name]&&!premium(tier))throw new Error('Este recurso exige um acesso Pro ativo.');return true}
  window.DroneHubCentralAccess={actualTier:actualTier,previewTier:previewTier,requireFeature:requireFeature};

  function records(fn){try{return typeof window[fn]==='function'?window[fn](window.uid||current().id||''):[]}catch(e){return []}}
  function esc(v){var n=document.createElement('span');n.textContent=String(v==null?'':v);return n.innerHTML}
  function weather(){return window.DroneHubFlightWeather||null}
  function selectedLimit(){var s=document.getElementById('droneSelect');if(!s)return 0;var o=s.options[s.selectedIndex];return Number(o&&o.dataset.limit)||Number(document.getElementById('manualWindLimit')&&document.getElementById('manualWindLimit').value)||0}
  function result(){var w=weather(),limit=selectedLimit();if(!w||!limit)return {label:'Selecione sua aeronave',cls:'attention',copy:'O limite do fabricante permite comparar vento e rajadas.'};var gust=Math.max.apply(null,w.daily.wind_gusts_10m_max||[0]);var ratio=gust/limit;return ratio<=.6?{label:'Favorável',cls:'',copy:'A previsão básica está dentro da faixa conservadora.'}:ratio<=1?{label:'Atenção',cls:'attention',copy:'Há vento ou rajadas que exigem cautela e avaliação do piloto.'}:{label:'Não recomendado',cls:'danger',copy:'A previsão ultrapassa o limite de vento cadastrado.'}}
  function locked(title,copy){return '<article class="tier-tool locked"><small>ANÁLISE PROFISSIONAL</small><strong>'+title+'</strong><span>'+copy+'</span><i class="tier-lock">▣ Recurso Pro</i></article>'}
  function tool(title,copy,href,label){return '<article class="tier-tool"><small>ANÁLISE PROFISSIONAL</small><strong>'+title+'</strong><span>'+copy+'</span>'+(href?'<a href="'+href+'">'+label+'</a>':'')+'</article>'}
  function comparison(){var rows=[['Clima atual','✓','✓'],['Previsão de 3 dias','✓','✓'],['Uma aeronave','✓','✓'],['Avaliação básica de vento','✓','✓'],['Previsão horária','—','✓'],['Índice de risco completo','—','✓'],['Documentos e SARPAS','—','✓'],['Baterias e autonomia','—','✓'],['Checklist e diário','—','✓'],['Briefing e relatórios','—','✓']];return '<table class="tier-compare"><thead><tr><th>Recurso</th><th>Free</th><th>Pro</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+r[0]+'</td><td class="'+(r[1]==='✓'?'tier-yes':'tier-no')+'">'+r[1]+'</td><td class="tier-yes">'+r[2]+'</td></tr>'}).join('')+'</tbody></table>'}
  function render(){var main=document.querySelector('.main.flight-deck')||document.querySelector('.main');if(!main)return;var old=document.getElementById('centralTierExperience');if(old)old.remove();var tier=previewTier(),isPremium=premium(tier),aircraft=records('getAircraft'),docs=records('getDocuments'),batteries=records('getBatteries'),missions=records('getMissions'),r=result();var shell=document.createElement('section');shell.id='centralTierExperience';shell.className='central-tier-shell';
    var basic='<section class="central-tier-head"><div><span class="central-tier-kicker">Sua análise de voo</span><h2>Clima compatível com sua aeronave.</h2><p>Local, previsão de três dias e limite de vento reunidos para uma decisão básica e objetiva.</p></div><span class="tier-pill">'+(tier==='admin'?'Central Admin':tier==='pro'?'Central Pro':'Central Free')+'</span></section>'+
      '<section class="central-tier-panel"><span class="central-tier-kicker">Consulta liberada</span><div class="tier-basic-grid"><article class="tier-metric"><small>Aeronave</small><strong>'+(aircraft[0]?esc(((aircraft[0].marca||'')+' '+(aircraft[0].modelo||'')).trim()):'Cadastre 1 aeronave')+'</strong><span>Comparação usa o limite oficial informado no cadastro.</span></article><article class="tier-metric"><small>Local</small><strong>'+esc(localStorage.getItem('dronehub_location_name')||'Rio de Janeiro, RJ')+'</strong><span>Condições atuais e próximos três dias.</span></article><article class="tier-metric"><small>Limite de vento</small><strong>'+(selectedLimit()?selectedLimit().toFixed(1).replace('.',',')+' km/h':'Aguardando aeronave')+'</strong><span>Vento e rajadas são comparados ao equipamento.</span></article><article class="tier-metric tier-result '+r.cls+'"><small>Resultado básico</small><strong>'+r.label+'</strong><span>'+r.copy+'</span></article></div><div class="tier-pro-note">O Drone Hub informa compatibilidade operacional; a decisão e a autorização oficial permanecem sob responsabilidade do piloto. <a href="https://sarpas.decea.mil.br/" target="_blank" rel="noopener" style="color:#63ddff">Acessar o SARPAS oficial →</a></div></section>';
    var proTools=isPremium?[
      tool('Previsão horária e bússola','Vento, direção, visibilidade, nuvens, precipitação e pôr do sol para a janela da missão.','central-voo.html#weatherContent','Ver meteorologia'),
      tool('Risco detalhado','Cruza clima, aeronave, documentação e contexto operacional.','central-voo.html#weatherContent','Ver análise'),
      tool('Frota e autonomia',aircraft.length+' aeronave(s), '+batteries.length+' bateria(s); autonomia relativa considera vento e temperatura.','aeronaves.html#fleetHealth','Abrir frota'),
      tool('Documentos e SARPAS',docs.length+' documento(s) e '+missions.length+' missão(ões) vinculáveis.','missoes.html','Vincular missão'),
      tool('Checklist, planejamento e diário','Salve a missão, conclua o checklist e forme o histórico automático.','missoes.html','Planejar operação'),
      tool('Briefing e pós-voo','Gere briefing operacional e relatório profissional em PDF ou DOCX.','documentos.html?template=briefing','Gerar documento')
    ].join(''):[locked('Previsão horária e bússola','Janela da missão, direção do vento e pôr do sol.'),locked('Índice de risco completo','Clima, documentos, frota e contexto operacional.'),locked('Baterias e autonomia','Ciclos, saúde e autonomia relativa ao ambiente.'),locked('Documentos e SARPAS','Vencimentos e autorização vinculada à missão.'),locked('Checklist e diário','Planejamento salvo e histórico automático.'),locked('Briefing e relatórios','PDF e DOCX para antes e depois da operação.')].join('');
    var upgrade=isPremium?'':'<div class="tier-upgrade"><div><strong>Sua consulta básica está pronta.</strong><p>O Pro verifica documentos, baterias, espaço aéreo, checklist e produz o briefing completo da operação.</p></div><a href="precos.html">Comparar Free e Pro</a></div>';
    var admin='';if(actualTier()==='admin'){var mode=previewTier();admin='<section class="central-tier-panel"><span class="central-tier-kicker">Diagnóstico administrativo</span><h2>Serviço e simulação de acesso</h2><div class="tier-diagnostics"><article class="tier-metric"><small>Provedor</small><strong>Open-Meteo</strong><span>Via Drone Hub Operations Worker</span></article><article class="tier-metric"><small>Atualização</small><strong id="tierLastUpdate">Aguardando</strong><span>Clima revalidado a cada 10 minutos</span></article><article class="tier-metric"><small>Estado</small><strong id="tierServiceState">Online</strong><span>Monitoramento da consulta atual</span></article><article class="tier-metric"><small>Sincronização</small><strong>'+aircraft.length+' / '+docs.length+'</strong><span>Aeronaves / documentos carregados</span></article></div><div class="admin-simulator"><button data-preview="admin" class="'+(mode==='admin'?'active':'')+'">Admin</button><button data-preview="pro" class="'+(mode==='pro'?'active':'')+'">Simular Pro</button><button data-preview="free" class="'+(mode==='free'?'active':'')+'">Simular Free</button></div></section>'}
    shell.innerHTML=basic+'<section class="central-tier-panel"><span class="central-tier-kicker">Análise profissional</span><h2>Antes, durante e depois do voo.</h2><p>Free informa se o clima é compatível com sua aeronave. Pro verifica se a operação inteira está pronta para acontecer.</p><div class="tier-pro-grid">'+proTools+'</div>'+upgrade+comparison()+'</section>'+admin;main.appendChild(shell);
    shell.querySelectorAll('[data-preview]').forEach(function(btn){btn.addEventListener('click',function(){sessionStorage.setItem('dronehub_admin_preview_tier',btn.dataset.preview);render()})});
  }
  document.addEventListener('DOMContentLoaded',async function(){await refresh();render();setTimeout(render,1200);window.addEventListener('dronehub:cloud-ready',render);window.addEventListener('change',function(e){if(e.target&&['droneSelect','flightDate'].indexOf(e.target.id)>=0)setTimeout(render,50)})});
  window.addEventListener('dronehub:weather-ready',render);
}());
