(function(){
  function onready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();}
  function get(key){try{return JSON.parse(localStorage.getItem(key)||'[]');}catch(e){return [];}}
  function store(v){localStorage.setItem('dronehub_fleet_health',JSON.stringify(v));}
  function aircraft(){return typeof getAircraft==='function'?getAircraft(window.uid):[];}
  function render(){var root=document.getElementById('fleetHealth');if(!root)return;var a=aircraft(), data=get('dronehub_fleet_health').filter(function(x){return x.userId===(window.uid||'local');});var cycles=data.map(function(x){return Number(x.cycles)||0;}), max=cycles.length?Math.max.apply(Math,cycles):0, safe=max<150?'Saudável':max<250?'Acompanhar':'Atenção';var health=a.length?Math.max(0,100-Math.max(0,max-80)/3):0;root.querySelector('#fleetScore').textContent=a.length?Math.round(health)+'%':'—';root.querySelector('#fleetStatus').textContent=a.length?safe:'Cadastre uma aeronave';root.querySelector('#fleetAircraft').textContent=a.length;root.querySelector('#fleetBatteries').textContent=data.length;root.querySelector('#fleetCycles').textContent=max?max+' ciclos':'—';var select=root.querySelector('#fleetAircraftSelect');select.innerHTML=a.length?a.map(function(x){return '<option value="'+x.id+'">'+(x.marca||'')+' '+(x.modelo||'')+'</option>';}).join(''):'<option value="">Cadastre uma aeronave primeiro</option>';}
  onready(function(){if(!window.isPro)return;var target=document.querySelector('.main > .card');if(!target)return;var section=document.createElement('section');section.id='fleetHealth';section.className='fleet-health';section.innerHTML='<div class="fleet-health__top"><div><div class="fleet-health__eyebrow">Saúde da frota</div><h3>Prontidão de aeronaves e baterias</h3><p>Monitore ciclos, firmware, seguro e manutenção antes de alocar uma aeronave em missão.</p></div><div class="fleet-health__score" id="fleetScore">—<small id="fleetStatus">Carregando</small></div></div><div class="fleet-health__grid"><div class="fleet-health__metric"><span>Aeronaves</span><b id="fleetAircraft">0</b></div><div class="fleet-health__metric"><span>Baterias registradas</span><b id="fleetBatteries">0</b></div><div class="fleet-health__metric"><span>Maior ciclo</span><b id="fleetCycles">—</b></div></div><form class="fleet-health__form" id="fleetForm"><select id="fleetAircraftSelect" aria-label="Aeronave"></select><input id="fleetCyclesInput" min="0" type="number" placeholder="Ciclos da bateria"><input id="fleetFirmware" type="text" placeholder="Firmware / manutenção"><button class="btn btn-primary" type="submit">Registrar</button></form>';
    target.insertAdjacentElement('afterend',section);render();section.querySelector('#fleetForm').addEventListener('submit',function(e){e.preventDefault();var aircraftId=section.querySelector('#fleetAircraftSelect').value;if(!aircraftId){alert('Cadastre uma aeronave antes de registrar a saúde da frota.');return;}var data=get('dronehub_fleet_health');data.push({id:Date.now().toString(),userId:window.uid||'local',aircraftId:aircraftId,cycles:Number(section.querySelector('#fleetCyclesInput').value)||0,firmware:section.querySelector('#fleetFirmware').value.trim(),registeredAt:new Date().toISOString()});store(data);section.querySelector('#fleetCyclesInput').value='';section.querySelector('#fleetFirmware').value='';render();});});
}());
